spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/yeogida
    username: sa
    password:
    driver-class-name: org.h2.Driver

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create-drop  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bd345a1db3ef5e1bb84f6bba050b7482
            client-secret: 5UKrRSZJUaKQKMDNBWdcwkwDcYRgR4bG
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#  h2:
#    console:
#      settings:
#        web-allow-others: true
#      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  header: Authorization
  secret: 0e7cd9f102c251f716731901621f0bfac6b3f4797a3a5c9de4806f184ec40cc106627dfe481e7f2cbc67569b2f62c8c61b2b7d6ca8193df585cd256aeea6baf1
